version: '3.5'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.2
    depends_on:
      - db
      - django
    networks:
      - app_network
    ports:
      - "7700:7700"
    volumes:
      - ./meilisearch_data:/data.ms
  db:
    image: postgres:15.1
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: redis:7.0.8
    networks:
      - redis_network

  django:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DJANGO_SECRET_KEY
    depends_on:
      - db
      - redis
    command: gunicorn learn_serbian.wsgi -c gunicorn.cfg.py
    volumes:
      - ./_app:/usr/src/app
    networks:
      - app_network
      - redis_network
    ports:
      - "80:8000"
    environment:
      - PYTHONUNBUFFERED=0
      - DJANGO_SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MEDIA_ROOT
      - MEDIA_URL
      - OPENAI_KEY
      - S3_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET_NAME
      - S3_REGION
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - MEILISEARCH_URL
      - MEILISEARCH_KEY

volumes:
  database_volume:

networks:
  app_network:
  redis_network:
